### ISSUE TITLE
Strangest glitch ever

### ISSUE THREAD

**Issue by TheRealMandMs05** [MJRLegends/MJRLegendsLib#1]
When I install it, and run minecraft, it quickly switches between the loading forge/mojang screen, and a screen that says "Extra planets is missing mods it depends on. Please install the mods below or remove Extra planets" and nothing else.

**Comment by MJRLegends** [comment]
This isnt a MJRLegendsLib thing

**Comment by MJRLegends** [comment]
![](https://i.gyazo.com/9e8074132e725167a04f6a7bb841229b.png) These are what you need for ExtraPlanets, your probably using a to older forge
