### ISSUE TITLE
1.1.7 crashes on server startup

### ISSUE THREAD

**Issue by Krotain** [MJRLegends/MJRLegendsLib#11]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
[Description of the issue]

1.1.7 of this lib mod crashes on server startup while 1.1.6 does not

### Steps to Reproduce Issue
Install galacticraft + extra planets + 1.1.7 of this mod
Launch server

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

https://pastebin.com/zHAJ2Qhi

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]

extraplanets 1.12.2-0.4.6
mjrlegendslib 1.12.2-1.1.7
Galacticraft versions 181 and 186 have the same results
Forge version 2768

**Where did this bug happen:** [Single Player or Server] Server

### Additional Information
[Any other information that may be able to help me with the problem]

The game will work fine running client side with 1.1.7 as far as I can tell but crashes on server startup. 1.1.6 works with 0.4.6 of extra planets as well as 0.4.5. I downloaded the mods from their official sites listed here

https://minecraft.curseforge.com/projects/extraplanets/files/2651041
https://minecraft.curseforge.com/projects/mjrlegendslib/files/2624411
https://micdoodle8.com/mods/galacticraft/downloads

**Comment by MJRLegends** [comment]
Update will be out in a few hours to fix this

**Comment by MJRLegends** [comment]
Fixed versions are out, you will need up update Collecting Rain mod too if you have it

**Comment by MJRLegends** [comment]
@Krotain Thanks for the bug report
