### ISSUE TITLE
signature b02331787272ec3515ebe63ecdeea0d746653468 is expected

### ISSUE THREAD

**Issue by yconselvan** [MJRLegends/MJRLegendsLib#14]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** YES!

### Description of Issue
Every time i try to use jars available in https://maven.mjrlegends.com/  i'm getting that signature b02331787272ec3515ebe63ecdeea0d746653468 is expected, and the jar is not loaded

### Steps to Reproduce Issue
1. Fresh install and setup minecraft server from forge-1.12.2-14.23.5.2768-installer.jar
2. Install latests galaticcraft jars from https://micdoodle8.com/mods/galacticraft/downloads

MicdoodleCore-1.12.2-4.0.2.190.jar
GalacticraftCore-1.12.2-4.0.2.190.jar
Galacticraft-Planets-1.12.2-4.0.2.190.jar

3. Install extraplanets from https://maven.mjrlegends.com/com/mjr/extraplanets/ExtraPlanets/1.12.2-0.5.0/ExtraPlanets-1.12.2-0.5.0.jar

4 - Install MJRLegendsLib from https://maven.mjrlegends.com/com/mjr/mjrlegendslib/MJRLegendsLib/1.12.2-1.1.6/MJRLegendsLib-1.12.2-1.1.6.jar

5 - Start the server

**Crash log/Log (if applicable):
https://pastebin.com/a7ULeNPT

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
MJRLegendsLib-1.12.2-1.1.6

**Where did this bug happen:** [Single Player or Server]
SERVER

### Additional Information
It seens to be some hardcoded signature hash

**Comment by MJRLegends** [comment]
Yes dont use them from my maven they are not where players should download them from

**Comment by yconselvan** [comment]
So what?

**Comment by MJRLegends** [comment]
There are not meant to be signed from the maven the game will run just fine. It causes a error/message in the log. Doesnt crash the game.

**Comment by MJRLegends** [comment]
The fact your downloading them from my maven rather than curseforge is just silly. The maven jars are there for developers not players

**Comment by yconselvan** [comment]
Thank's!  Have found in courseforge!
