### ISSUE TITLE
extra planets

### ISSUE THREAD

**Issue by yaboi1234567891234** [MJRLegends/MJRLegendsLib#15]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
[Description of the issue]

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/Minecraft/crash-log/

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]

**Where did this bug happen:** [Single Player or Server]

### Additional Information
[Any other information that may be able to help me with the problem]
it wont let me load into minecraft im using 1.12.2 with this mob

**Comment by MJRLegends** [comment]
If this issue report is for ExtraPlanets you have put it in the wrong issue tracker and to be honest you havent even took the time to supply me the details for the issue. Sorry i cant be anything with this issue report
