### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by Domimike1234** [MJRLegends/MJRLegendsLib#19]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
Me and my friends are playing modded minecraft and when we added more mods including this mod the game crashes.

### Steps to Reproduce Issue
1. Launch minecraft
2. Game crashes

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
[crash-2023-02-13_16.16.32-client.txt](https://github.com/MJRLegends/MJRLegendsLib/files/10723161/crash-2023-02-13_16.16.32-client.txt)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.12.2

**Where did this bug happen:** game and server cashes

**Comment by MJRLegends** [comment]
Your using the dev version of the mod which is for development environments, please download the normal jar file

https://www.curseforge.com/minecraft/mc-mods/mjrlegendslib/download/3344068
