### ISSUE TITLE
MJRLEGENDS LIB not up to date

### ISSUE THREAD

**Issue by DarkMatterXCIX** [MJRLegends/MJRLegendsLib#2]
Server tells me to have version 1.12.2-1.0.6 or up.. but i do?

**Comment by MJRLegends** [comment]
That version is on curseforge yeah theres no reason why it wouldn't work

**Comment by DarkMatterXCIX** [comment]
Ill send u crash report then.....

**Comment by MJRLegends** [comment]
Ok post it here using pastebin

**Comment by DarkMatterXCIX** [comment]
https://pastebin.com/uFGJxNhu
also, i was told this is a issue with extra planets and Custom Mob Spawner. but it is a extra planets problem cause when i remove it it works

**Comment by MJRLegends** [comment]
Why you posting it here then? This is more MJRLegendsLib??

**Comment by MJRLegends** [comment]
Please make a bug report on the correct issue tracker
