### ISSUE TITLE
[1.8+] Server Side crash

### ISSUE THREAD

**Issue by ElSaam** [MJRLegends/MJRLegendsLib#3]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.138.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  CreativePatchingLoader (CreativeCore_v1.9.18_mc1.12.2.jar)
  NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  MtqFixPlugin (mtqfix-1.12.2-1.1.0.jar)
  LoadingPlugin (sampler-1.73.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (FoamFix-1.12.2-0.8.2-Anarchy.jar)
  SpongeCoremod (spongeforge-1.12.2-2611-7.1.0-BETA-2918.jar)
Contact their authors BEFORE contacting forge

// Oh - I know what I did wrong!

Time: 19/02/18 12:46
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from MJRLegendsLib (mjrlegendslib)
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/client/model/ICustomModelLoader
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:522)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:278)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:256)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:560)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:568)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:97)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:332)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.client.model.ICustomModelLoader
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 35 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/resources/IResourceManagerReloadListener
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 37 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.resources.IResourceManagerReloadListener
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 41 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zjl000(MinecraftServer.java:4013)

-- Sponge PhaseTracker --
Details:
	Cause Stack: [Empty stack]
Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zjl000(MinecraftServer.java:4013)
	at net.minecraft.server.MinecraftServer.func_71230_b(MinecraftServer.java:887)
	at net.minecraft.server.dedicated.DedicatedServer.func_71230_b(DedicatedServer.java:370)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:556)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 6225362776 bytes (5936 MB) / 7267155968 bytes (6930 MB) up to 7267155968 bytes (6930 MB)
	JVM Flags: 2 total; -Xmx7G -Xms7G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.2.2611 62 mods loaded, 61 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version                     | Source                                                        | Signature                                |
	|:----- |:------------------- |:--------------------------- |:------------------------------------------------------------- |:---------------------------------------- |
	| UC    | minecraft           | 1.12.2                      | minecraft.jar                                                 | None                                     |
	| UC    | mcp                 | 9.42                        | minecraft.jar                                                 | None                                     |
	| UC    | FML                 | 8.0.99.99                   | spigot.jar                                                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | forge               | 14.23.2.2611                | spigot.jar                                                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | creativecoredummy   | 1.0.0                       | minecraft.jar                                                 | None                                     |
	| UC    | micdoodlecore       |                             | minecraft.jar                                                 | None                                     |
	| UC    | spongeapi           | 7.1.0-SNAPSHOT-6aa4e43      | spongeforge-1.12.2-2611-7.1.0-BETA-2918.jar                   | None                                     |
	| UC    | sponge              | 1.12.2-2611-7.1.0-BETA-2918 | spongeforge-1.12.2-2611-7.1.0-BETA-2918.jar                   | None                                     |
	| UC    | foamfixcore         | 7.7.4                       | minecraft.jar                                                 | None                                     |
	| UC    | securitycraft       | v1.8.4.1                    | [1.12.x]+SecurityCraft+v1.8.4.1.jar                           | None                                     |
	| UC    | aiimprovements      | 0.0.1.3                     | AIImprovements-1.12-0.0.1b3.jar                               | None                                     |
	| UC    | architecturecraft   | @VERSION@                   | architecturecraft-1.12-2.68.jar                               | None                                     |
	| UC    | biomesoplenty       | 7.0.1.2314                  | BiomesOPlenty-1.12.2-7.0.1.2314-universal.jar                 | None                                     |
	| UC    | ic2                 | 2.8.16-ex112                | industrialcraft-2-2.8.16-ex112.jar                            | de041f9f6187debbc77034a344134053277aa3b0 |
	| UC    | galacticraftcore    | 4.0.1.138                   | GalacticraftCore-1.12.2-4.0.1.138.jar                         | None                                     |
	| UC    | galacticraftplanets | 4.0.1.138                   | Galacticraft-Planets-1.12.2-4.0.1.138.jar                     | None                                     |
	| UE    | mjrlegendslib       | 1.12.2-1.0.8                | MJRLegendsLib-1.12.2-1.0.8.jar                                | None                                     |
	| UE    | blankplanet         | 0.1-1.12.2                  | BlankPlanet-0.1-1.12.2.jar                                    | None                                     |
	| UC    | buildcraftlib       | 7.99.14                     | buildcraft-7.99.14.jar                                        | None                                     |
	| UC    | buildcraftcore      | 7.99.14                     | buildcraft-7.99.14.jar                                        | None                                     |
	| UC    | buildcraftbuilders  | 7.99.14                     | buildcraft-7.99.14.jar                                        | None                                     |
	| UC    | buildcraftenergy    | 7.99.14                     | buildcraft-7.99.14.jar                                        | None                                     |
	| UC    | buildcraftfactory   | 7.99.14                     | buildcraft-7.99.14.jar                                        | None                                     |
	| UC    | buildcraftrobotics  | 7.99.14                     | buildcraft-7.99.14.jar                                        | None                                     |
	| UC    | buildcraftsilicon   | 7.99.14                     | buildcraft-7.99.14.jar                                        | None                                     |
	| UC    | buildcrafttransport | 7.99.14                     | buildcraft-7.99.14.jar                                        | None                                     |
	| UC    | creativecore        | 1.9.9                       | CreativeCore_v1.9.18_mc1.12.2.jar                             | None                                     |
	| UC    | cyberware           | 0.2.10.9                    | cyberware-1.12.2-0.2.10.9.jar                                 | 67a0e286dc0d4b502f3c92ac20b953517b52d0a9 |
	| UC    | ptrmodellib         | 1.0.0                       | Decocraft-2.5.4_1.12.2.jar                                    | None                                     |
	| UC    | props               | 2.5.4                       | Decocraft-2.5.4_1.12.2.jar                                    | None                                     |
	| UC    | cdm                 | 0.2.1                       | device-mod-0.2.1-1.12.2.jar                                   | None                                     |
	| UC    | dynamictrees        | 1.12.2-0.7.4                | DynamicTrees-1.12.2-0.7.4.jar                                 | None                                     |
	| UE    | extraplanets        | 1.12.2-0.2.2                | ExtraPlanets-1.12.2-0.2.2.jar                                 | None                                     |
	| UC    | fastasyncworldedit  | development                 | FastAsyncWorldEdit-sponge112-18.02.15-7141cc4-1012-19.1.7.jar | None                                     |
	| UC    | worldedit           |                             | FastAsyncWorldEdit-sponge112-18.02.15-7141cc4-1012-19.1.7.jar | None                                     |
	| UC    | fl                  | 2.11.1                      | fl-2.11.1.jar                                                 | None                                     |
	| UC    | foamfix             | 0.8.2-1.12.2                | FoamFix-1.12.2-0.8.2-Anarchy.jar                              | None                                     |
	| UC    | forgelin            | 1.6.0                       | Forgelin-1.6.0.jar                                            | None                                     |
	| UC    | cfm                 | 4.1.5                       | furniture-4.1.5-1.12.2.jar                                    | None                                     |
	| UC    | ichunutil           | 7.1.4                       | iChunUtil-1.12.2-7.1.4.jar                                    | None                                     |
	| UC    | gravitygun          | 7.0.0                       | GravityGun-1.12.2-7.0.1.jar                                   | None                                     |
	| UC    | longfallboots       | 1.2.1a                      | longfallboots-1.2.1a.jar                                      | None                                     |
	| UC    | malisiscore         | 1.12.2-6.4.0                | malisiscore-1.12.2-6.4.0.jar                                  | None                                     |
	| UC    | malisisdoors        | 1.12.2-7.3.0                | malisisdoors-1.12.2-7.3.0.jar                                 | None                                     |
	| UC    | mcflux              | 3.11.1                      | mcflux-3.11.1.jar                                             | None                                     |
	| UC    | mts                 | 9.0.1                       | Minecraft+Transport+Simulator-1.12.2-9.0.1.jar                | None                                     |
	| UC    | modelloader         | 1.0.5                       | modelloader-1.0.5.jar                                         | None                                     |
	| UC    | moreplanets         | 2.0.12                      | More-Planets-1.12.2-2.0.12-GC132.jar                          | b3468b224a74e296555ad7efeb35f482e6f445de |
	| UC    | moreplanetsextras   | 1.12.2-1.0                  | MorePlanetsExtras-1.12.2-1.0.jar                              | None                                     |
	| UC    | nucleus             | 1.3.1-S7.0                  | Nucleus-1.3.1-S7.0-MC1.12.2-plugin.jar                        | None                                     |
	| UC    | parachutemod        | 1.7.4                       | parachutemod-wasd-1.12.2-1.7.4-439.jar                        | None                                     |
	| UC    | placeableitems      | 3.2                         | placeableitems-3.2.jar                                        | None                                     |
	| UE    | planetprogression   | 1.12.2-0.1.0                | PlanetProgression-1.12.2-0.1.0.jar                            | None                                     |
	| UC    | portalgun           | 7.0.0                       | PortalGun-1.12.2-7.0.1.jar                                    | None                                     |
	| UC    | projecte            | 1.12-PE1.0.0                | ProjectE-1.12-PE1.2.0.jar                                     | None                                     |
	| UC    | redstonepaste       | 1.7.5                       | redstonepaste-mc1.12-1.7.5.jar                                | None                                     |
	| UC    | rewired             | 1.12.2                      | ReWIRED-1.0.3.jar                                             | None                                     |
	| UC    | sampler             | 1.73                        | sampler-1.73.jar                                              | None                                     |
	| UC    | thutcore            | 5.16.1                      | thutcore-1.12.2-5.16.1.jar                                    | None                                     |
	| UC    | thutcore_compat     | 1.0                         | thutcore-1.12.2-5.16.1.jar                                    | None                                     |
	| UC    | thuttech            | 6.0.15                      | thuttech-1.12.2-6.0.15.jar                                    | None                                     |
	| UD    | mtqfix              | 1.1.0                       | minecraft.jar                                                 | None                                     |

	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.138.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
ForgelinPlugin (Forgelin-1.6.0.jar)
  
CreativePatchingLoader (CreativeCore_v1.9.18_mc1.12.2.jar)
  
NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  net.fybertech.nwr.NWRTransformer
MtqFixPlugin (mtqfix-1.12.2-1.1.0.jar)
  jmn.mods.mtqfix.AsmTransformer
LoadingPlugin (sampler-1.73.jar)
  
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (FoamFix-1.12.2-0.8.2-Anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
SpongeCoremod (spongeforge-1.12.2-2611-7.1.0-BETA-2918.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.138.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  CreativePatchingLoader (CreativeCore_v1.9.18_mc1.12.2.jar)
  NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  MtqFixPlugin (mtqfix-1.12.2-1.1.0.jar)
  LoadingPlugin (sampler-1.73.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (FoamFix-1.12.2-0.8.2-Anarchy.jar)
  SpongeCoremod (spongeforge-1.12.2-2611-7.1.0-BETA-2918.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 19/02/18 12:42
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from MJRLegendsLib (mjrlegendslib)
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/client/model/ICustomModelLoader
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:522)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:278)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:256)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:560)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:568)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:97)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:332)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.client.model.ICustomModelLoader
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 35 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/resources/IResourceManagerReloadListener
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 37 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.resources.IResourceManagerReloadListener
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 41 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zjl000(MinecraftServer.java:4013)

-- Sponge PhaseTracker --
Details:
	Cause Stack: [Empty stack]
Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zjl000(MinecraftServer.java:4013)
	at net.minecraft.server.MinecraftServer.func_71230_b(MinecraftServer.java:887)
	at net.minecraft.server.dedicated.DedicatedServer.func_71230_b(DedicatedServer.java:370)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:556)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 6340628712 bytes (6046 MB) / 7276068864 bytes (6939 MB) up to 7276068864 bytes (6939 MB)
	JVM Flags: 2 total; -Xmx7G -Xms7G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.2.2611 61 mods loaded, 60 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version                     | Source                                                        | Signature                                |
	|:----- |:------------------- |:--------------------------- |:------------------------------------------------------------- |:---------------------------------------- |
	| UC    | minecraft           | 1.12.2                      | minecraft.jar                                                 | None                                     |
	| UC    | mcp                 | 9.42                        | minecraft.jar                                                 | None                                     |
	| UC    | FML                 | 8.0.99.99                   | spigot.jar                                                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | forge               | 14.23.2.2611                | spigot.jar                                                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | creativecoredummy   | 1.0.0                       | minecraft.jar                                                 | None                                     |
	| UC    | micdoodlecore       |                             | minecraft.jar                                                 | None                                     |
	| UC    | spongeapi           | 7.1.0-SNAPSHOT-6aa4e43      | spongeforge-1.12.2-2611-7.1.0-BETA-2918.jar                   | None                                     |
	| UC    | sponge              | 1.12.2-2611-7.1.0-BETA-2918 | spongeforge-1.12.2-2611-7.1.0-BETA-2918.jar                   | None                                     |
	| UC    | foamfixcore         | 7.7.4                       | minecraft.jar                                                 | None                                     |
	| UC    | securitycraft       | v1.8.4.1                    | [1.12.x]+SecurityCraft+v1.8.4.1.jar                           | None                                     |
	| UC    | aiimprovements      | 0.0.1.3                     | AIImprovements-1.12-0.0.1b3.jar                               | None                                     |
	| UC    | architecturecraft   | @VERSION@                   | architecturecraft-1.12-2.68.jar                               | None                                     |
	| UC    | biomesoplenty       | 7.0.1.2314                  | BiomesOPlenty-1.12.2-7.0.1.2314-universal.jar                 | None                                     |
	| UC    | ic2                 | 2.8.16-ex112                | industrialcraft-2-2.8.16-ex112.jar                            | de041f9f6187debbc77034a344134053277aa3b0 |
	| UC    | galacticraftcore    | 4.0.1.138                   | GalacticraftCore-1.12.2-4.0.1.138.jar                         | None                                     |
	| UC    | galacticraftplanets | 4.0.1.138                   | Galacticraft-Planets-1.12.2-4.0.1.138.jar                     | None                                     |
	| UE    | mjrlegendslib       | 1.12.2-1.0.9                | MJRLegendsLib-1.12.2-1.0.9.jar                                | None                                     |
	| UE    | blankplanet         | 0.1-1.12.2                  | BlankPlanet-0.1-1.12.2.jar                                    | None                                     |
	| UC    | buildcraftlib       | 7.99.14                     | buildcraft-7.99.14.jar                                        | None                                     |
	| UC    | buildcraftcore      | 7.99.14                     | buildcraft-7.99.14.jar                                        | None                                     |
	| UC    | buildcraftbuilders  | 7.99.14                     | buildcraft-7.99.14.jar                                        | None                                     |
	| UC    | buildcraftenergy    | 7.99.14                     | buildcraft-7.99.14.jar                                        | None                                     |
	| UC    | buildcraftfactory   | 7.99.14                     | buildcraft-7.99.14.jar                                        | None                                     |
	| UC    | buildcraftrobotics  | 7.99.14                     | buildcraft-7.99.14.jar                                        | None                                     |
	| UC    | buildcraftsilicon   | 7.99.14                     | buildcraft-7.99.14.jar                                        | None                                     |
	| UC    | buildcrafttransport | 7.99.14                     | buildcraft-7.99.14.jar                                        | None                                     |
	| UC    | creativecore        | 1.9.9                       | CreativeCore_v1.9.18_mc1.12.2.jar                             | None                                     |
	| UC    | cyberware           | 0.2.10.9                    | cyberware-1.12.2-0.2.10.9.jar                                 | 67a0e286dc0d4b502f3c92ac20b953517b52d0a9 |
	| UC    | ptrmodellib         | 1.0.0                       | Decocraft-2.5.4_1.12.2.jar                                    | None                                     |
	| UC    | props               | 2.5.4                       | Decocraft-2.5.4_1.12.2.jar                                    | None                                     |
	| UC    | cdm                 | 0.2.1                       | device-mod-0.2.1-1.12.2.jar                                   | None                                     |
	| UC    | dynamictrees        | 1.12.2-0.7.4                | DynamicTrees-1.12.2-0.7.4.jar                                 | None                                     |
	| UC    | fastasyncworldedit  | development                 | FastAsyncWorldEdit-sponge112-18.02.15-7141cc4-1012-19.1.7.jar | None                                     |
	| UC    | worldedit           |                             | FastAsyncWorldEdit-sponge112-18.02.15-7141cc4-1012-19.1.7.jar | None                                     |
	| UC    | fl                  | 2.11.1                      | fl-2.11.1.jar                                                 | None                                     |
	| UC    | foamfix             | 0.8.2-1.12.2                | FoamFix-1.12.2-0.8.2-Anarchy.jar                              | None                                     |
	| UC    | forgelin            | 1.6.0                       | Forgelin-1.6.0.jar                                            | None                                     |
	| UC    | cfm                 | 4.1.5                       | furniture-4.1.5-1.12.2.jar                                    | None                                     |
	| UC    | ichunutil           | 7.1.4                       | iChunUtil-1.12.2-7.1.4.jar                                    | None                                     |
	| UC    | gravitygun          | 7.0.0                       | GravityGun-1.12.2-7.0.1.jar                                   | None                                     |
	| UC    | longfallboots       | 1.2.1a                      | longfallboots-1.2.1a.jar                                      | None                                     |
	| UC    | malisiscore         | 1.12.2-6.4.0                | malisiscore-1.12.2-6.4.0.jar                                  | None                                     |
	| UC    | malisisdoors        | 1.12.2-7.3.0                | malisisdoors-1.12.2-7.3.0.jar                                 | None                                     |
	| UC    | mcflux              | 3.11.1                      | mcflux-3.11.1.jar                                             | None                                     |
	| UC    | mts                 | 9.0.1                       | Minecraft+Transport+Simulator-1.12.2-9.0.1.jar                | None                                     |
	| UC    | modelloader         | 1.0.5                       | modelloader-1.0.5.jar                                         | None                                     |
	| UC    | moreplanets         | 2.0.12                      | More-Planets-1.12.2-2.0.12-GC132.jar                          | b3468b224a74e296555ad7efeb35f482e6f445de |
	| UC    | moreplanetsextras   | 1.12.2-1.0                  | MorePlanetsExtras-1.12.2-1.0.jar                              | None                                     |
	| UC    | nucleus             | 1.3.1-S7.0                  | Nucleus-1.3.1-S7.0-MC1.12.2-plugin.jar                        | None                                     |
	| UC    | parachutemod        | 1.7.4                       | parachutemod-wasd-1.12.2-1.7.4-439.jar                        | None                                     |
	| UC    | placeableitems      | 3.2                         | placeableitems-3.2.jar                                        | None                                     |
	| UE    | planetprogression   | 1.12.2-0.1.1                | PlanetProgression-1.12.2-0.1.1.jar                            | None                                     |
	| UC    | portalgun           | 7.0.0                       | PortalGun-1.12.2-7.0.1.jar                                    | None                                     |
	| UC    | projecte            | 1.12-PE1.0.0                | ProjectE-1.12-PE1.2.0.jar                                     | None                                     |
	| UC    | redstonepaste       | 1.7.5                       | redstonepaste-mc1.12-1.7.5.jar                                | None                                     |
	| UC    | rewired             | 1.12.2                      | ReWIRED-1.0.3.jar                                             | None                                     |
	| UC    | sampler             | 1.73                        | sampler-1.73.jar                                              | None                                     |
	| UC    | thutcore            | 5.16.1                      | thutcore-1.12.2-5.16.1.jar                                    | None                                     |
	| UC    | thutcore_compat     | 1.0                         | thutcore-1.12.2-5.16.1.jar                                    | None                                     |
	| UC    | thuttech            | 6.0.15                      | thuttech-1.12.2-6.0.15.jar                                    | None                                     |
	| UD    | mtqfix              | 1.1.0                       | minecraft.jar                                                 | None                                     |

	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.138.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
ForgelinPlugin (Forgelin-1.6.0.jar)
  
CreativePatchingLoader (CreativeCore_v1.9.18_mc1.12.2.jar)
  
NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  net.fybertech.nwr.NWRTransformer
MtqFixPlugin (mtqfix-1.12.2-1.1.0.jar)
  jmn.mods.mtqfix.AsmTransformer
LoadingPlugin (sampler-1.73.jar)
  
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (FoamFix-1.12.2-0.8.2-Anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
SpongeCoremod (spongeforge-1.12.2-2611-7.1.0-BETA-2918.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)

**Comment by MJRLegends** [comment]
Thanks for the bug reports, updates will be out once curseforge approves them in a few hours time :D

**Comment by MJRLegends** [comment]
All been approved now
