### ISSUE TITLE
[1.8+] Console spam in console

### ISSUE THREAD

**Issue by MJRLegends** [MJRLegends/MJRLegendsLib#7]
See https://github.com/MJRLegends/Planet-Progression/issues/28

**Comment by MasterEnderman** [comment]
Hopefully the update also fixes the console spam if you look at some rockets.

**Comment by MJRLegends** [comment]
Fixed will be coming out today/in the next hour

**Comment by MJRLegends** [comment]
Sorry for the delay :D

**Comment by MJRLegends** [comment]
Updates have been released, will be showing when they get approved :D
