### ISSUE TITLE
MJRLegendsLib Prevents the Game from Opening

### ISSUE THREAD

**Issue by Tornadodex** [MJRLegends/MJRLegendsLib#8]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
I Downloaded Extra Planets 1.12.2 and MJRLegendsLib 1.12.2 and now Minecraft wont open.

### Steps to Reproduce Issue
1. Download MJRLegendsLib-1.12.2-1.1.5 and Extra Planets 1.12-0.4.1
2. Run Forge 1.12

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.12.2-1.1.5

**Where did this bug happen:** The Game Didn't Even Start

### Additional Information
I'm on Windows 10. I've tried to fix it by using almost every version of Extra Planets 1.12 and MJRLegendsLib 1.12, none of them work. Once I take both Extra Planets and MJRLegendsLib out of the mod folder, the game opens and runs perfectly fine!

**Comment by MJRLegends** [comment]
Not enough detail. You need to include log files

**Comment by Tornadodex** [comment]
Here's the crash log

https://paste.ubuntu.com/p/WvSgtjtm4Q/

**Comment by MJRLegends** [comment]
Sorry but thats something else. That's nothing to with me

**Comment by MJRLegends** [comment]
If you read the log you posted you will see the issue as i doesnt say anything about my mods
