### ISSUE TITLE
incompatibility issue (1.12.2)

### ISSUE THREAD

**Issue by paradoxmeem** [MJRLegends/MJRLegendsLib#9]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
Incompatible with Flans mod, tested and checked issues

### Steps to Reproduce Issue
1. install flans and mjrlegendslib correctly
2. start game

**Crash log/Log (if applicable):**
https://pastebin.com/ewQqRcMb

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
1.12.2
**Where did this bug happen:** [Single Player or Server]
single player
### Additional Information
[Any other information that may be able to help me with the problem]
might be conflicting with flans mod apocalypse more so than other parts, not entirely sure.
also ive tested these mods standalone, issue persists.

**Comment by MJRLegends** [comment]
I dont see anything erroring for MJRLegendsLib which means its on the flans mod side please report to them

**Comment by MJRLegends** [comment]
Ok yea the issue is between Galacticraft and Flans mod. Idk why you thought it was MJRLegendsLib. The issue is they are both registering fluids as sulphuricAcid

**Comment by paradoxmeem** [comment]
sorry for troubling you, thought it was mjrlegendslib.

**Comment by MJRLegends** [comment]
As i said please report it to flans mod
